#这是插件的配置文件，所有的设置都在这里
Setting:
  Debug_Mode: true
  #这个选项可以完全禁用或启用经验修补，当设置为true时，经验修补可以使用，当设置为false时，经验修补没有作用
  AHI_Mend: true

  Slow_Mend:
    #是否启用缓慢修补功能
    Enable: true

    #经验修补的减弱系数，将决定经验修补消耗的经验量。数字越大消耗越多，换算大约为“1/[最大值]”
    Mitigation_Factor: 5

  #限制经验修补次数
  Max_Mend_Limit:

    #是否启用，启用将限制经验修补的修补次数，如果到达次数物品将不会被修补
    Enable: true

    #最大修补次数，此参数为可触发的修补次数，玩家吸收经验就会增加，而不是触发修补
    Max_Number: 1000

    #在修补次数耗尽后，是否给玩家发送信息
    Deactivate_Message: true

    #发送的信息内容
    Broken_Message: 你的这件装备已经很破旧了，是时候换一个了。

    #装备达到上限后是否更改名称
    Change_Item_Name: true

    #更改名字前缀的内容
    Broken_Prefix: §7破损的-

    #这是限制提示的内容，请不要在开服后随意更改！！！这条内容决定了插件识别的内容！！！
    #如果更改需要将旧名称填入“Old_Mend_Frequency_Lore_Name”内
    Mend_Frequency_Lore_Name: §9剩余修补次数：

    #旧名称，列表内的名称将与正常名称一起生效减少次数，但无法进行其他操作。
    Old_Mend_Frequency_Lore_Name:
    #- "123："
